Blockly.Toolboxes ||= new Object(null);

Blockly.Toolboxes.STANDARD_TOOLBOX = {
    "kind": "categoryToolbox",
    "contents": [{
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "create_chick"
        }, {
            "kind": "BLOCK",
            "type": "show_actor"
        }, {
            "kind": "BLOCK",
            "type": "move_actor_to_x_y"
        }, {
            "kind": "BLOCK",
            "type": "sleep"
        }],
        "name": "Actors",
        "colour": "#9fa55b"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "controls_if"
        }, {
            "kind": "BLOCK",
            "type": "logic_compare"
        }, {
            "kind": "BLOCK",
            "type": "logic_operation"
        }, {
            "kind": "BLOCK",
            "type": "logic_negate"
        }, {
            "kind": "BLOCK",
            "type": "logic_boolean"
        }, {
            "kind": "BLOCK",
            "type": "logic_null"
        }, {
            "kind": "BLOCK",
            "type": "logic_ternary"
        }],
        "name": "Logic",
        "colour": "#5b80a5"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "controls_repeat_ext"
        }, {
            "kind": "BLOCK",
            "type": "controls_whileUntil"
        }, {
            "kind": "BLOCK",
            "type": "controls_for"
        }, {
            "kind": "BLOCK",
            "type": "controls_forEach"
        }, {
            "kind": "BLOCK",
            "type": "controls_flow_statements"
        }],
        "name": "Loops",
        "colour": "#5ba55b"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "math_number"
        }, {
            "kind": "BLOCK",
            "type": "math_arithmetic"
        }, {
            "kind": "BLOCK",
            "type": "math_single"
        }, {
            "kind": "BLOCK",
            "type": "math_trig"
        }, {
            "kind": "BLOCK",
            "type": "math_constant"
        }, {
            "kind": "BLOCK",
            "type": "math_number_property"
        }, {
            "kind": "BLOCK",
            "type": "math_round"
        }, {
            "kind": "BLOCK",
            "type": "math_on_list"
        }, {
            "kind": "BLOCK",
            "type": "math_modulo"
        }, {
            "kind": "BLOCK",
            "type": "math_constrain"
        }, {
            "kind": "BLOCK",
            "type": "math_random_int"
        }, {
            "kind": "BLOCK",
            "type": "math_random_float"
        }],
        "name": "Math",
        "colour": "#5b67a5"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "text"
        }, {
            "kind": "BLOCK",
            "type": "text_join"
        }, {
            "kind": "BLOCK",
            "type": "text_append"
        }, {
            "kind": "BLOCK",
            "type": "text_length"
        }, {
            "kind": "BLOCK",
            "type": "text_isEmpty"
        }, {
            "kind": "BLOCK",
            "type": "text_indexOf"
        }, {
            "kind": "BLOCK",
            "type": "text_charAt"
        }, {
            "kind": "BLOCK",
            "type": "text_getSubstring"
        }, {
            "kind": "BLOCK",
            "type": "text_changeCase"
        }, {
            "kind": "BLOCK",
            "type": "text_trim"
        }, {
            "kind": "BLOCK",
            "type": "text_print"
        }, {
            "kind": "BLOCK",
            "type": "text_prompt_ext"
        }],
        "name": "Text",
        "colour": "#5ba58c"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "lists_create_with"
        }, {
            "kind": "BLOCK",
            "type": "lists_create_with"
        }, {
            "kind": "BLOCK",
            "type": "lists_repeat"
        }, {
            "kind": "BLOCK",
            "type": "lists_length"
        }, {
            "kind": "BLOCK",
            "type": "lists_isEmpty"
        }, {
            "kind": "BLOCK",
            "type": "lists_indexOf"
        }, {
            "kind": "BLOCK",
            "type": "lists_getIndex"
        }, {
            "kind": "BLOCK",
            "type": "lists_setIndex"
        }, {
            "kind": "BLOCK",
            "type": "lists_getSublist"
        }, {
            "kind": "BLOCK",
            "type": "lists_split"
        }, {
            "kind": "BLOCK",
            "type": "lists_sort"
        }],
        "name": "Lists",
        "colour": "#745ba5"
    }, {
        "kind": "CATEGORY",
        "contents": [{
            "kind": "BLOCK",
            "type": "colour_picker"
        }, {
            "kind": "BLOCK",
            "type": "colour_random"
        }, {
            "kind": "BLOCK",
            "type": "colour_rgb"
        }, {
            "kind": "BLOCK",
            "type": "colour_blend"
        }],
        "name": "Colour",
        "colour": "#a5745b"
    }, {
        "kind": "SEP"
    }, {
        "kind": "CATEGORY",
        "name": "Variables",
        "colour": "#a55b80",
        "custom": "VARIABLE"
    }, {
        "kind": "CATEGORY",
        "name": "Functions",
        "colour": "#995ba5",
        "custom": "PROCEDURE"
    }
    ]
};
